[build]
builder = "NIXPACKS"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate --run-syncdb && python manage.py seed_trails && gunicorn himaltrails.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
healthcheckPath = "/api/trails/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
