# Generated by Django 6.0.5 on 2026-05-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('highlights', models.TextField(help_text='One highlight per line')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elevation_gain_m', models.IntegerField()),
                ('max_altitude_m', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=20)),
                ('trek_style', models.CharField(choices=[('teahouse', 'Tea House'), ('camping', 'Camping'), ('luxury', 'Luxury Lodge')], default='teahouse', max_length=20)),
                ('start_point', models.CharField(default='Kathmandu', max_length=200)),
                ('end_point', models.CharField(default='Kathmandu', max_length=200)),
                ('best_seasons', models.CharField(help_text='e.g. Mar-May, Sep-Dec', max_length=200)),
                ('permits_required', models.BooleanField(default=True)),
                ('guide_required', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('altitude_m', models.IntegerField(blank=True, null=True)),
                ('walk_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trails.trail')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
