# Generated by Django 6.0.5 on 2026-05-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('permit_type', models.CharField(choices=[('tims', 'TIMS Card'), ('national_park', 'National Park Entry'), ('conservation', 'Conservation Area Permit'), ('restricted', 'Restricted Area Permit'), ('municipal', 'Municipality / Local Entry')], max_length=30)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('where_to_buy', models.CharField(max_length=400)),
                ('notes', models.TextField(blank=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='trails.trail')),
            ],
            options={
                'ordering': ['cost_usd'],
            },
        ),
        migrations.CreateModel(
            name='Teahouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('altitude_m', models.IntegerField(blank=True, null=True)),
                ('price_usd_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_usd_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_hot_shower', models.BooleanField(default=False)),
                ('day_on_trail', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teahouses', to='trails.trail')),
            ],
            options={
                'ordering': ['altitude_m'],
            },
        ),
    ]
