# Generated by Django 6.0.5 on 2026-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trail_latitude_trail_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='condition_status',
            field=models.CharField(choices=[('open', 'Open'), ('partial', 'Partial restrictions'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='trail',
            name='condition_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
