# Generated by Django 6.0.5 on 2026-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_trail_condition_notes_trail_condition_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('specialties', models.CharField(blank=True, help_text='comma-separated', max_length=400)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('price_per_day_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('trails', models.ManyToManyField(blank=True, related_name='guides', to='trails.trail')),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
